---
title: "GraficoTema3 GrupoI"
output:
  pdf_document: default
  html_document: default
date: "2024-02-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
#Cargamos las librerías
library(tidyverse)
library(knitr)
library(htmltools)
library(plotly)
library(ggplot2)
library(datasets)
library(dplyr)
library(extrafont)
library(stringr)

#Cargamos fuentes de letra adicionales
loadfonts(device = "win", quiet = TRUE)

#Cambiamos el tipo de fecha
covid_data <- read_csv("./data/owid-covid-data.csv", col_types = cols(date = col_date(format = "%Y-%m-%d")))

#Filtramos países
selected_countries <- c("United States", "Italy", "France", "Germany", "Canada", "Japan", "United Kingdom", "Spain")

#Creamos data frame con los datos del gráfico
selected_data <- covid_data %>%
  filter(location %in% selected_countries) %>%
  rename(country = location, deaths_per_million = new_deaths_smoothed_per_million)

#Coloreamos con los códigos de R
country_colors <- c(
  "United States" = "#7A4C9A",
  "Italy" = "#2B938D",
  "France" = "#B03608",
  "Germany" = "#399C66",
  "Canada" = "#88313A",
  "Japan" = "#47566E",
  "United Kingdom" = "#D42773",
  "Spain" =  "red"
)

#Creamos el gráfico, y añadimos todos los parámetros necesarios para que se asemeje al gráfico dado
grafico_covid <- ggplot(selected_data, aes(x = date, y = deaths_per_million, color = country, group = country)) + 
  geom_line(data = filter(selected_data, country == "Spain"), size = 1) + 
  geom_path() + 
  scale_y_continuous(breaks = seq(0, 18, by = 2)) +
  scale_x_date(date_labels = "%b %d, %Y", breaks = seq(min(selected_data$date), max(selected_data$date), length.out = 6)) +
  geom_hline(yintercept = c(2, 4, 6, 8, 10, 12, 14, 16, 18), linetype = "dotted", color = "gray", size = 0.5) +
  scale_color_manual(values = country_colors) + 
  labs(x = "", y = "", title = "Daily new confirmed COVID-19 death per million people", 
       subtitle = "7-day rolling average. For some countries the number of confirmed deaths is much lower than the \n true number of deaths. This is because of limited testing and challenges in the attribution of the \n cause of death.", 
       caption = "Source: Johns Hopkins University CSSE COVID-19 Data" ) +
  theme_bw() +
  theme(
    plot.title = element_text(family = "Times New Roman", size = 18, color = "#555555"),
    plot.subtitle = element_text(color = "#818181"),
    plot.caption = element_text(hjust = 0, color = "#818181")
  )
#Mostramos el gráfico
grafico_covid

#Convertimos el gráfico estándar en un gráfico interactivo
#grafico_interactivo <- ggplotly(grafico_covid) %>%
  #layout(plot_bgcolor = "white", paper_bgcolor = "white")

#Lo mostramos y comprobamos que, efectivamente, funciona
#grafico_interactivo




```

